# Generated by Django 5.2.3 on 2025-08-09 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationresult',
            name='version',
        ),
        migrations.AddField(
            model_name='tradedocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.tradedocument')),
            ],
            options={
                'unique_together': {('document', 'field_name')},
            },
        ),
        migrations.DeleteModel(
            name='DocumentVersion',
        ),
    ]
